### PR TITLE
migrate to decimal package

### PR DESCRIPTION
**Pull request by a14n**
Following up to https://github.com/noojee/money.dart/issues/54#issuecomment-970085733 here's an attemp to use the decimal package.

(IMHO this package should be merged into money2 directly and remained an implementation detail of money2 inside `src/`)

### CODE REVIEW

**Comment by bsutton** [comment]
@al4n thanks for the PR.

I will need a few days to work through the implications. 

My  preference is to not re-implement the decimal package  and this looks like it might be a reasonable middle ground.

The things that jump out at me.
Fixed needs to be a public package as its original intent was to provide a method to pass in exchange rates which is part of the public api.

Additionally a core objective I had was to provide a consistent interface between money and whatever decimal package was used so the user didn't have to learn to differing api. I think you approach will over come this concern.

I have a minor concern that the decimal package is less performant given the use of two big ints but I think the reality is that for 99% of money users this just isn't a consideration.

I need to get my head around whether the differing approach to handling scale will create any unexpected rounding issues.
This centres around that if I have a value 1.20 and I'm doing some maths on it I don't want the underlying maths to be done on the value 1.201 as the underlying implementation is storing additional precision.  I've not had enough time with your code to understand how you have dealt this but it should be resolvable if you haven't already addressed it.

Summary: I'm very open to the proposal, give me few days to dig into the details.
I believe fixed will need to be a public package.

**Comment by pryshrm** [comment]
If a user of the money package could do something like this, then that would be awesome:

```
String amount  = '201.03'; //value may be coming from json
String ccy = 'USD'; //value may be coming from json

Money m1 = Money(amount, ccy);
Money m2 =m1*100; //arithmetic operations involving ints or BigInt
Money m2 = m1*m2; //arithmetic operations involving only Money
String digitalAmount = m1.toDigitalString(); //assigns '201.3' to digitalAmount
String formattedAmount =  m1.toString();  //assigns '$201.3' to formattedString

```

**Comment by bsutton** [comment]
Multiplying money X money actually makes no sense. Your are multiplying it
by a quantity.

Part of the reason for introducing fixed is to allow you to multiply money
by a fixed scale quality.

I don't know what toDigitalstring is supposed to do but the rest is already
supported.

**Comment by bsutton** [comment]
I think I realised what the digital method is, you want to format the
string without a $.

That is what the format method is for.

m.format('#.#')

**Comment by bsutton** [comment]
@a14n time permitting I will pull this tonight.

Greatly appreciate the effort and feedback.

**Comment by pryshrm** [comment]
If I can create Money using Money(Decimal amount, String ccy) without providing a formatter, then I should be able to split money back into its original constituents without providing a formatter. So, I would expect ( by expect, I mean, as a user of Money package,  not as in I am demanding it..lol very thankful for what you already have created), it to have two methods to get those two items back - a simple numeric string (the toDigitalString or a better name) and the currency code. 

Providing formatter pattern to get would pollute the package user's code. For example, I am getting the amount and ccy from a REST API in JSON format and I am expected to send amount and ccy back in the same for to the back end. Usage of Money is entirely a front end thing. 

Money*Money may not make much sense but Money + Money would easily make sense. My point is, basic mathematical operations (+ - * /) should be supported.

**Comment by pryshrm** [comment]
> but the rest is already supported.

You mean, this works now?

```
String amount  = '201.03'; //value may be coming from json
String ccy = 'USD'; //value may be coming from json
Money m1 = Money(amount, ccy);
```

**Pull request merged**
